; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
;lib_extra_dirs = libweitwapp/tests
;src_dir = libweitwapp

[env:test-arduino-uno-blink]
; Blinking on-board LED (13) on Arduino
; PRECONDITIONS: none
; TEST: the on-board LED blinks
platform = atmelavr
board = uno
framework = arduino
build_src_filter =
    +<libweitwapp/tests/misc/arduino/arduino-blink.test.cpp>

[env:test-arduino-uno-hal-gpio]
; Blinking LED on Arduino
; tests libweitwapp/hal
; Precondition:
; - none
; Test result:
; - the on-board LED blinks
platform = atmelavr
board = uno
framework = arduino
build_flags =
    -D LIBWEITWAPP_HAL_BUILD_ARDUINO   
build_src_filter =
    +<libweitwapp/tests/hal/arduino/gpio.hal.test.cpp>
    +<libweitwapp/hal/arduino/gpio.hal.c>
 
[env:test-arduino-uno-hal-timer]
; Blinking LED on Arduino
; tests libweitwapp/hal
; Precondition:
; - none
; Test result:
; - the on-board LED blinks
platform = atmelavr
board = uno
framework = arduino
build_src_filter =
    +<libweitwapp/tests/hal/arduino/timer.hal.test.cpp>
    +<libweitwapp/hal/arduino/timer.hal.c>
    

[env:test-arduino-uno-hal-timer2]
; Blinking LED on Arduino
; tests libweitwapp/hal
; Precondition:
; - none
; Test result:
; - the on-board LED blinks
platform = atmelavr
board = uno
framework = arduino
build_src_filter =
    +<libweitwapp/tests/hal/arduino/timer.hal.test2.cpp>
    +<libweitwapp/hardware/led.c>
    +<libweitwapp/hardware/dio.c>
    +<libweitwapp/hal/arduino/gpio.hal.c>
    +<libweitwapp/hal/arduino/timer.hal.c>
    

[env:test-arduino-uno-hal-timer3]
; Blinking LED on Arduino
; tests libweitwapp/hal
; Precondition:
; - none
; Test result:
; - the on-board LED blinks
platform = atmelavr
board = uno
framework = arduino
build_src_filter =
    +<libweitwapp/tests/hal/arduino/timer.hal.test3.cpp>
    +<libweitwapp/hardware/led.c>
    +<libweitwapp/hardware/dio.c>
    +<libweitwapp/hal/arduino/gpio.hal.c>
    +<libweitwapp/hal/arduino/timer.hal.c>
    

[env:test-arduino-uno-hardware-dout1]
; ARDUINO on-board LED on PIN13 blinks
; PRECONDITIONS: 
; - DI2 MODE_ACTIVE_HIGH
; TEST: Compile and run the program
; - PASSED: LED blinks 
; - FAILED: 
platform = atmelavr
board = uno
framework = arduino
build_src_filter =
    +<libweitwapp/tests/hardware/arduino/dio1.test.cpp>
    +<libweitwapp/hal/arduino/gpio.hal.c>
    +<libweitwapp/hardware/dio.c>
    

[env:test-arduino-uno-hardware-dout2x1]
; Two blinking LEDs connected to an Arduino
; tests libweitwapp/hardware/dio: aktiv-high and aktiv-low
; Precondition:
; - connect LED1 (PIN8) with R to GND -> LIBWEITWAPP_DIO_MODE_ACTIVE_HIGH
; - connect LED2 (PIN4) with R to Vcc -> LIBWEITWAPP_DIO_MODE_ACTIVE_LOW
; Test result:
; - LED1 and LED2 are blinking synchronously
platform = atmelavr
board = uno
framework = arduino
build_src_filter =
    +<libweitwapp/tests/hardware/arduino/dio2.test.cpp>
    +<libweitwapp/hal/arduino/gpio.hal.c>
    +<libweitwapp/hardware/dio.c>
    

[env:test-arduino-uno-hardware-dout2x2]
; Two blinking LEDs connected to an Arduino
; tests libweitwapp/hardware/dio: aktiv-high and aktiv-low
; Precondition:
; - connect LED1 (PIN8) with R to GND -> LIBWEITWAPP_DIO_MODE_ACTIVE_HIGH
; - connect LED2 (PIN4) with R to GND -> LIBWEITWAPP_DIO_MODE_ACTIVE_LOW
; Test result:
; - the LEDs flash alternately
platform = atmelavr
board = uno
framework = arduino
build_src_filter =
    +<libweitwapp/tests/hardware/arduino/dio2.test.cpp>
    +<libweitwapp/hal/arduino/gpio.hal.c>
    +<libweitwapp/hardware/dio.c>
    

[env:test-arduino-uno-hardware-din1]
; If DI1 or DI2 is active the Arduino on-board LED on PIN 13 is switch on
; PRECONDITIONS for eacht test:
; - DI1 MODE_ACTIVE_HIGH, connect to GND
; - DI2 MODE_ACTIVE_LOW, connect to Vss
; TEST DI1: connect DI1 to Vss
; - PASSED: LED lights up
; - FAILED: 
; TEST DI2: connect DI2 to GND
; - PASSED: LED lights up
; - FAILED: 
platform = atmelavr
board = uno
framework = arduino
build_src_filter =
    +<libweitwapp/tests/hardware/arduino/din1.test.cpp>
    +<libweitwapp/hal/arduino/gpio.hal.c>
    +<libweitwapp/hardware/dio.c>
    

[env:test-arduino-uno-hardware_button]
; The Arudino on-board LED is switched on while a button is pressed
; tests libweitwapp/hardware/button
; Precondition:
; - Connect BUTTON1 (PIN8) with R to GND -> LIBWEITWAPP_DIO_MODE_ACTIVE_HIGH
; - Connect BUTTON2 (PIN4) with R to VCC -> LIBWEITWAPP_DIO_MODE_ACTIVE_LOW
; Test result:
; - The Arduino on-board LED is turned one while at least one button is pressed.
platform = atmelavr
board = uno
framework = arduino
build_src_filter =
    +<libweitwapp/tests/hardware/arduino/button.test.cpp>
    +<libweitwapp/hal/arduino/gpio.hal.c>
    +<libweitwapp/hal/arduino/timer.hal.c>
    +<libweitwapp/hardware/dio.c>
    +<libweitwapp/hardware/button.c>
    

[env:test-arduino-uno-hardware-led1]
; LED on Arduino lights up
; tests libweitwapp/hardware/led
; Precondition:
; - none
; Test result:
; - the on-board LED lights up
platform = atmelavr
board = uno
framework = arduino
build_src_filter =
    +<libweitwapp/tests/hardware/arduino/led1.test.cpp>
    +<libweitwapp/hal/arduino/gpio.hal.c>
    +<libweitwapp/hardware/dio.c>
    +<libweitwapp/hardware/led.c>
    

[env:test-arduino-uno-hardware-led2]
; LED on Arduino blinks
; tests libweitwapp/hardware/led
; Precondition:
; - none
; Test result:
; - the on-board LED blinks
platform = atmelavr
board = uno
framework = arduino
build_src_filter =
    +<libweitwapp/tests/hardware/arduino/led2.test.cpp>
    +<libweitwapp/hal/arduino/gpio.hal.c>
    +<libweitwapp/hardware/dio.c>
    +<libweitwapp/hardware/led.c>
    

[env:test-arduino-uno-button_3leds_breakout]
; TODO: Beschreibe Test
platform = atmelavr
board = uno
framework = arduino
build_src_filter =
    +<libweitwapp/tests/breakouts/arduino/button_3leds_breakout/button_3leds_breakout.test.cpp>
    +<libweitwapp/hal/arduino/gpio.hal.c>
    +<libweitwapp/hardware/dio.c>
    +<libweitwapp/hardware/led.c>
    +<libweitwapp/hardware/button.c>
    +<libweitwapp/hal/arduino/timer.hal.c>
    +<libweitwapp/breakouts/button_3leds.breakout.c>
    

[env:test-arduino-uno-lcd1602-gpio]
; TODO: Beschreibe Test
platform = atmelavr
board = uno
framework = arduino
build_src_filter =
    +<libweitwapp/tests/hardware/arduino/lcd1602.gpio.test.cpp>
    +<libweitwapp/hal/arduino/gpio.hal.c>
    +<libweitwapp/hal/arduino/timer.hal.c>
    +<libweitwapp/hardware/dio.c>
    +<libweitwapp/hardware/lcd1602.gpio.c>
    

[env:test-arduino-uno-hal-adc_01]
; TODO: Beschreibe Test
platform = atmelavr
board = uno
framework = arduino
build_src_filter =
    +<libweitwapp/tests/hal/arduino/adc.hal.test_01.cpp>
    +<libweitwapp/hal/arduino/adc.hal.c>
    +<libweitwapp/hal/arduino/timer.hal.c>
    
[env:test-arduino-uno-hcsr04_01]
; Reads the measured distance from a HC-SCR04 sensor and writes it to serial COM
; PRECONDITION:
; - connect the HC-SR04 sensor to Arduino
; TEST: 
; Measure the distance of an object to the sensor and compare it with the reading on serial COM
; - PASSED: reading equals approx. distance
; - FAILED: reading differes from distance
platform = atmelavr
board = uno
framework = arduino
build_src_filter =
    +<libweitwapp/tests/hardware/arduino/hcsr04.test.cpp>
    +<libweitwapp/hardware/hcsr04.c>
    +<libweitwapp/hal/arduino/timer.hal.c>
    +<libweitwapp/hal/arduino/gpio.hal.c>
    +<libweitwapp/hardware/dio.c>
    

    